openapi: 3.0.3
info:
  title: Search Service API
  version: "2024-01-01"
  description: |
    Defines the SearchService which supports operations related to search indices and queries within the retail industry.

paths:
  /indexes/{indexId}/queries:
    post:
      summary: Create a new query within an index and retrieve the initial set of results.
      operationId: createQuery
      parameters:
        - in: path
          name: indexId
          required: true
          schema:
            type: string
            pattern: "^[A-Za-z0-9]+$"
          description: Represents a unique identifier for an index.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQueryRequest'
      responses:
        '201':
          description: The created query and initial set of results.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateQueryResponse'

components:
  schemas:
    CreateQueryRequest:
      type: object
      required:
        - indexId
        - query
      properties:
        indexId:
          type: string
          pattern: "^[A-Za-z0-9]+$"
          description: The unique identifier for the index.
        query:
          type: string
          description: The search query string.

    CreateQueryResponse:
      type: object
      required:
        - page
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Hit'
          description: List of search results (hits) returned by the query.
        page:
          type: integer
          description: The page number of the query results.

    Hit:
      type: object
      additionalProperties:
        type: string
      description: Represents a search result from a query.

    Hits:
      type: array
      items:
        $ref: '#/components/schemas/Hit'
      description: List of hits; each item in the list represents a search result from a query.

    IndexId:
      type: string
      pattern: "^[A-Za-z0-9]+$"
      description: Represents a unique identifier for an index.

    QueryId:
      type: string
      pattern: "^[A-Za-z0-9]+$"
      description: Represents a unique identifier for a query within an index.

    FacetId:
      type: string
      pattern: "^[A-Za-z0-9]+$"
      description: Represents a unique identifier for a facet in a query.

    Strings:
      type: array
      items:
        type: string
      description: A list of strings.
