openapi: 3.0.0
info:
  title: Procurement Service
  description: |
    The Procurement Service generates Request for Quote (RFQ) content.
    This service automates the generation of boilerplate text included in an RFQ
    before it goes out to vendors for quoting.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /rfq:
    post:
      summary: Generate RFQ content
      description: |
        Generates a detailed set of requests for products and/or services along with requirements.
        This response is used to generate an RFQ document that vendors can reply to.
      requestBody:
        description: Description of the overall products/services to be quoted
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/RFQResponse'
              
components:
  schemas:
    RFQResponse:
      type: object
      properties:
        rfqContent:
          type: string
          description: The generated content for the RFQ document
        disclaimer:
          type: string
          description: Legal disclaimer text to include in the RFQ
        responseInstructions:
          type: string 
          description: Instructions for vendors on how to respond to the RFQ
